export default {
  HOME_LOADED_ACTION: 'HOME_LOADED_ACTION',
  FETCH_AUTHORS_REQUEST: 'FETCH_AUTHORS_REQUEST',
  FETCH_AUTHORS_SUCCESS: 'FETCH_AUTHORS_SUCCESS',
  FETCH_AUTHORS_CANCEL: 'FETCH_AUTHORS_CANCEL',
  FETCH_AUTHORS_ERROR: 'FETCH_AUTHORS_ERROR',
  FETCH_AUTHOR_REQUEST: 'FETCH_AUTHOR_REQUEST',
  FETCH_AUTHOR_SUCCESS: 'FETCH_AUTHOR_SUCCESS',
  FETCH_AUTHOR_CANCEL: 'FETCH_AUTHOR_CANCEL',
  FETCH_AUTHOR_ERROR: 'FETCH_AUTHOR_ERROR'
}
