export default {
  HOME_LOADED_ACTION: 'HOME_LOADED_ACTION',

  FETCH_AUTHORS_REQUEST: 'FETCH_AUTHORS_REQUEST',
  FETCH_AUTHORS_SUCCESS: 'FETCH_AUTHORS_SUCCESS',
  FETCH_AUTHORS_CANCEL: 'FETCH_AUTHORS_CANCEL',
  FETCH_AUTHORS_ERROR: 'FETCH_AUTHORS_ERROR',
  FETCH_AUTHOR_REQUEST: 'FETCH_AUTHOR_REQUEST',
  FETCH_AUTHOR_SUCCESS: 'FETCH_AUTHOR_SUCCESS',
  FETCH_AUTHOR_CANCEL: 'FETCH_AUTHOR_CANCEL',
  FETCH_AUTHOR_ERROR: 'FETCH_AUTHOR_ERROR',

  SENSORS_LOAD_ACTION: 'SENSORS_LOAD_ACTION',
  SENSORS_FETCH_START: 'SENSORS_FETCH_START',
  SENSORS_FETCH_SUCCESS: 'SENSORS_FETCH_SUCCESS',
  SENSORS_FETCH_FAIL: 'SENSORS_FETCH_FAIL',

  SENSORS_UPDATE_ACTION: 'SENSORS_UPDATE_ACTION',

  SENSOR_CHANGE_STATUS_ACTION: 'SENSOR_CHANGE_STATUS_ACTION',
  SENSOR_CHANGE_STATUS_START: 'SENSOR_CHANGE_STATUS_START',
  SENSOR_CHANGE_STATUS_SUCCESS: 'SENSOR_CHANGE_STATUS_SUCCESS',
  SENSOR_CHANGE_STATUS_FAIL: 'SENSOR_CHANGE_STATUS_FAIL',

  ADD_SENSOR_REQUEST: 'ADD_SENSOR_REQUEST',

  LIST_CLICKED: 'LIST_CLICKED',
  MAP_CLICKED: 'MAP_CLICKED',
  POINT_CLICKED: 'POINT_CLICKED',

  DB_ADD_POINT: 'DB_ADD_POINT',
  DB_ADD_POINT_START: 'DB_ADD_POINT_START',
  DB_ADD_POINT_SUCCESS: 'DB_ADD_POINT_SUCCESS',
  DB_ADD_POINT_FAIL: 'DB_ADD_POINT_FAIL',

  DB_UPDATE_ADD_ERROR_POINTS: 'DB_UPDATE_ADD_ERROR_POINTS',
  DB_UPDATE_REMOVE_ERROR_POINTS: 'DB_UPDATE_REMOVE_ERROR_POINTS',

  DB_REMOVE_POINT: 'DB_REMOVE_POINT',
  DB_REMOVE_POINT_START: 'DB_REMOVE_POINT_START',
  DB_REMOVE_POINT_SUCCESS: 'DB_REMOVE_POINT_SUCCESS',
  DB_REMOVE_POINT_FAIL: 'DB_REMOVE_POINT_FAIL',

  SENSORS_REFRESH_ACTION: 'SENSORS_REFRESH_ACTION',
  SENSORS_REFRESH_START: 'SENSORS_REFRESH_START',
  SENSORS_REFRESH_SUCCESS: 'SENSORS_REFRESH_SUCCESS',
  SENSORS_REFRESH_FAIL: 'SENSORS_REFRESH_FAIL',

  NOTIFICATIONS_FETCH_REQUEST: 'NOTIFICATIONS_FETCH_REQUEST',
  NOTIFICATIONS_FETCH_SUCCESS: 'NOTIFICATIONS_FETCH_SUCCESS',
  NOTIFICATIONS_FETCH_FAIL: 'NOTIFICATIONS_FETCH_FAIL',

  NOTIFICATIONS_CHECK: 'NOTIFICATIONS_CHECK',
  NOTIFICATIONS_CHECK_SUCCESS: 'NOTIFICATIONS_CHECK_SUCCESS',

  NOTIFICATIONS_UPDATE: 'NOTIFICATIONS_UPDATE',
  NOTIFICATIONS_UPDATE_SUCCESS: 'NOTIFICATIONS_UPDATE_SUCCESS',
  NOTIFICATIONS_UPDATE_FAIL: 'NOTIFICATIONS_UPDATE_FAIL',
  NOTIFICATIONS_UPDATE_CONTINUE: 'NOTIFICATIONS_UPDATE_CONTINUE',

  NOTIFICATION_DRAWER_OPEN: 'NOTIFICATION_DRAWER_OPEN',
  NOTIFICATION_DRAWER_CLOSE: 'NOTIFICATION_DRAWER_CLOSE'
}
